version: "3.8"

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.3
    ports:
      - 9200:9200
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - es-net
    volumes:
      - es-data:/usr/share/elasticsearch/data

networks:
  es-net:
    driver: bridge

volumes:
  es-data: